"""Bundled email-domain presets for submission protection.

``DISPOSABLE_DOMAINS`` covers the throwaway providers that account for the bulk of bot signups;
``PERSONAL_DOMAINS`` covers consumer webmail. Both are conservative allow-by-default lists — a miss is a
submission that lands in the inbox as usual, never a rejection — so keep them to well-known names.
"""

DISPOSABLE_DOMAINS: frozenset[str] = frozenset(
    {
        "10minutemail.com",
        "10minutemail.net",
        "20minutemail.com",
        "33mail.com",
        "anonbox.net",
        "burnermail.io",
        "byom.de",
        "dispostable.com",
        "discard.email",
        "dropmail.me",
        "emailondeck.com",
        "fakeinbox.com",
        "fakemail.net",
        "getairmail.com",
        "getnada.com",
        "guerrillamail.com",
        "guerrillamail.net",
        "guerrillamail.org",
        "guerrillamailblock.com",
        "harakirimail.com",
        "inboxkitten.com",
        "jetable.org",
        "mail-temp.com",
        "mail.tm",
        "mailcatch.com",
        "maildrop.cc",
        "mailinator.com",
        "mailinator.net",
        "mailnesia.com",
        "mailnull.com",
        "mailsac.com",
        "mintemail.com",
        "mohmal.com",
        "mytemp.email",
        "nowmymail.com",
        "sharklasers.com",
        "spam4.me",
        "spamgourmet.com",
        "temp-mail.io",
        "temp-mail.org",
        "tempail.com",
        "tempinbox.com",
        "tempmail.com",
        "tempmail.net",
        "tempmailo.com",
        "tempr.email",
        "throwawaymail.com",
        "trashmail.com",
        "trashmail.de",
        "trashmail.me",
        "yopmail.com",
        "yopmail.fr",
        "yopmail.net",
    }
)

PERSONAL_DOMAINS: frozenset[str] = frozenset(
    {
        "aol.com",
        "att.net",
        "comcast.net",
        "gmail.com",
        "googlemail.com",
        "gmx.com",
        "gmx.de",
        "hotmail.co.uk",
        "hotmail.com",
        "icloud.com",
        "live.com",
        "mac.com",
        "mail.com",
        "me.com",
        "msn.com",
        "outlook.com",
        "pm.me",
        "proton.me",
        "protonmail.com",
        "yahoo.co.uk",
        "yahoo.com",
        "ymail.com",
        "zoho.com",
    }
)
