{{- if eq .Values.mode "combined" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "marvin.fullname" . }}
  labels:
    {{- include "marvin.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.http }}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- end }}
  - port: {{ .Values.service.frontendPort }}
    targetPort: frontend
    protocol: TCP
    name: frontend
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.frontend }}
    nodePort: {{ .Values.service.nodePorts.frontend }}
    {{- end }}
  selector:
    {{- include "marvin.selectorLabels" . | nindent 4 }}
{{- end }}
