"""workflow source recipe

Revision ID: 128961a76aa8
Revises: 64cbb6adc4cd
Create Date: 2026-10-10 13:41:30.216465

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "128961a76aa8"
down_revision: str | None = "64cbb6adc4cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_automations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_recipe", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("source_recipe_version", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_workspace_automations_source_recipe"), ["source_recipe"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspace_automations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_automations_source_recipe"))
        batch_op.drop_column("source_recipe_version")
        batch_op.drop_column("source_recipe")

    # ### end Alembic commands ###
