"""add groups.backup_key_encrypted

Revision ID: a79fa1345639
Revises: 8a73900e8fe4
Create Date: 2026-07-25 16:55:36.746567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = 'a79fa1345639'
down_revision: Union[str, None] = '8a73900e8fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_key_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('backup_key_encrypted')

    # ### end Alembic commands ###
