"""token lookup for API tokens and site clients

Revision ID: 64cbb6adc4cd
Revises: aacf9dc0ec21
Create Date: 2026-10-10 13:01:55.214735

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "64cbb6adc4cd"
down_revision: str | None = "aacf9dc0ec21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_clients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token_lookup", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_api_clients_token_lookup"), ["token_lookup"], unique=True)

    with op.batch_alter_table("long_live_tokens", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token_lookup", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_long_live_tokens_token_lookup"), ["token_lookup"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("long_live_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_long_live_tokens_token_lookup"))
        batch_op.drop_column("token_lookup")

    with op.batch_alter_table("api_clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_clients_token_lookup"))
        batch_op.drop_column("token_lookup")

    # ### end Alembic commands ###
