"""push subscriptions and user push preferences: Web Push for the admin app

Schema (additive):
  - ``push_subscriptions`` — one row per browser or phone a user turned push on in (Profile →
    Notifications): the push service endpoint (unique), the browser's encryption keys, a device label, and
    the sender's bookkeeping (last used / last success, consecutive failures). Deleted with the user;
  - ``users.push_preferences`` — which kinds of push the user takes; null takes the defaults.

Revision ID: 51102e463fce
Revises: f5cd32b5a3ff
Create Date: 2026-10-07 21:01:03.929492

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = "51102e463fce"
down_revision: str | None = "f5cd32b5a3ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("user_id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.String(length=255), nullable=False),
        sa.Column("auth", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("last_used_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("last_success_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("created_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint", name="uq_push_subscriptions_endpoint"),
    )
    with op.batch_alter_table("push_subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_push_subscriptions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_push_subscriptions_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("push_preferences", sa.JSON(none_as_null=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("push_preferences")

    with op.batch_alter_table("push_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_push_subscriptions_user_id"))
        batch_op.drop_index(batch_op.f("ix_push_subscriptions_created_at"))

    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
