"""auth throttles for sign-in and password-reset

Revision ID: aacf9dc0ec21
Revises: b7d3e5f1a9c2
Create Date: 2026-10-09 21:20:25.258066

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import marvin.db.migration_types

# revision identifiers, used by Alembic.
revision: str = "aacf9dc0ec21"
down_revision: str | None = "b7d3e5f1a9c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_throttles",
        sa.Column("id", marvin.db.migration_types.GUID(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=320), nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("window_start", marvin.db.migration_types.NaiveDateTime(), nullable=False),
        sa.Column("locked_until", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("created_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.Column("update_at", marvin.db.migration_types.NaiveDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key", name="uq_auth_throttles_scope_key"),
    )
    with op.batch_alter_table("auth_throttles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_throttles_created_at"), ["created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_throttles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_throttles_created_at"))

    op.drop_table("auth_throttles")
    # ### end Alembic commands ###
