"""event_log workspace_id nullable for system events

Revision ID: e4ede8d3bfc3
Revises: e49ab4346b7b
Create Date: 2026-07-26 18:29:02.554747

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e4ede8d3bfc3'
down_revision: str | None = 'e49ab4346b7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.alter_column('workspace_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.alter_column('workspace_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
